### ISSUE TITLE
UART Baudrate

### ISSUE THREAD

**Issue by 7h0ma5** [rwth-afu/RasPagerC9000#1]
Mit dem 8 MHz-Quarz sind 57600 baud leider nur mit einer Abweichung von 2.1 % möglich. Dazu kommt dann noch die Abweichung des Taktes vom Raspberry Pi, welche sich entweder positiv oder negativ darauf auswirken kann. Ich schlage vor, die Baudrate entweder auf 38400 baud oder auf 76800 baud zu ändern, da die Abweichung dann nur 0.2 % beträgt.

Mögliche Baudraten für f<sub>osc</sub> = 8 MHz:
<table>
  <tr>
    <th></th>
    <th colspan="2">U2X = 0</th>
    <th colspan="2">U2X = 1</th>
  </tr>
  <tr>
    <th>Baudrate</th>
    <th>UBRR</th>
    <th>Error</th>
    <th>UBRR</th>
    <th>Error</th>
  </tr>
  <tr>
    <td>9600</td>
    <td><b>51</b></td>
    <td><b>0.2 %</b></td>
    <td><b>103</b></td>
    <td><b>0.2 %</b></td>
  </tr>
  <tr>
    <td>14400</td>
    <td>34</td>
    <td>-0.8 %</td>
    <td>68</td>
    <td>0.6 %</td>
  </tr>
  <tr>
    <td>19200</td>
    <td><b>25</b></td>
    <td><b>0.2 %</b></td>
    <td><b>51</b></td>
    <td><b>0.2 %</b></td>
  </tr>
  <tr>
    <td>28800</td>
    <td>16</td>
    <td>2.1 %</td>
    <td>34</td>
    <td>-0.8 %</td>
  </tr>
  <tr>
    <td>38400</td>
    <td><b>12</b></td>
    <td><b>0.2 %</b></td>
    <td><b>25</b></td>
    <td><b>0.2 %</b></td>
  </tr>
  <tr>
    <td>57600</td>
    <td>8</td>
    <td>-3.5 %</td>
    <td>16</td>
    <td>2.1 %</td>
  </tr>
  <tr>
    <td>76800</td>
    <td>6</td>
    <td>-7.0 %</td>
    <td><b>12</b></td>
    <td><b>0.2 %</b></td>
  </tr>
  <tr>
    <td>115200</td>
    <td>3</td>
    <td>8.5 %</td>
    <td>8</td>
    <td>-3.5 %</td>
  </tr>
</table>

**Comment by dh3wr** [comment]
OK, wir nehmen dann 76800 Baud.
Marvin, bitte ebenfalls in der Java-Software ändern.
Thomas, hast du es geschafft den AVR zur programmieren?

**Comment by dh3wr** [comment]
Nach Absprache mit Marvin wird die Baudrate ein Config-Parameter im Configfile. 76k8 sind unter Umständen mit der Java-Lib nicht möglich. Die möglichen Baudraten werden im Configfile als Kommentar aufgeführt.

**Comment by 7h0ma5** [comment]
In der config.h-Datei gibt es jetzt auch die Option, die Baudrate einzustellen, standardmäßig ist momentan 38400 eingestellt.

@dh3wr Das Programmieren des AVR hat ohne Probleme funktioniert, die Software ist auch schon fertig und muss nur noch am C9000 getestet werden, mit dem Oszilloskop sieht aber alles schon gut aus. Da am Reset-Pin des AVR kein Pull-Up-Widerstand vorhanden ist, muss man den GPIO0 bzw. Pin 11 des Headers auf High setzten, damit der AVR startet. Zum einfachen Testen habe ich dafür die Targets "start" und "stop" im Makefile eingefügt. Wie man die Firmware flasht steht im Readme im "software/atmega"-Verzeichnis.

**Comment by dh3wr** [comment]
@7h0ma5 : Sehr schön, dann werde ich für morgen einen C9000 zum Testen mal vorbereiten. Die Fkt. der gelben LED hatte ich als "Es sind noch Daten im Buffer zum Aussenden drin". Ist das so programmiert?

Es kann noch sein, dass der Ausgang des POCSAG invertiert werden muss. Kann man das noch in der config.h einbauen?

**Comment by menzerath** [comment]
> Da am Reset-Pin des AVR kein Pull-Up-Widerstand vorhanden ist, muss man den GPIO0 bzw. Pin 11 des Headers auf High setzten, damit der AVR startet.

@7h0ma5 Soll sich da die Java-Anwendung drum kümmern?

**Comment by 7h0ma5** [comment]
@dh3wr Momentan zeigt die grüne LED an, dass der AVR läuft, die rote LED, dass PTT aktiv ist und die gelbe LED, ob gerade eine 1 oder 0 gesendet wird, so wie die RX/TX LEDs bei einem Arduino. Ich kann das aber gerne ändern.

@MarvinMenzerath Ja, das wäre am einfachsten. Ich hatte das auch schon als Kommentar zu einem Commit geschrieben, eigentlich müsste GitHub dann eine Benachrichtigung verschicken: https://github.com/rwth-afu/RasPagerC9000/commit/afc333ca16bf2674587427343b46328bf42fc67b#commitcomment-19646730

**Comment by menzerath** [comment]
Oh, dann hab ich das wohl übersehen...
Die Änderung ist jetzt in Commit 5738b1af648758c43531df412ecd4444987289ab und in der [neuen JAR](https://github.com/rwth-afu/RasPagerC9000/blob/master/software/raspager-java/bin/2016-11-02_15-33_RasPagerC9000.jar) enthalten.

**Comment by 7h0ma5** [comment]
@dh3wr Mit dem Commit 69eaeebadf20d84ec1042e806df4037292dbc06c kann man jetzt in der config.h über die Option INVERT_BITS das Invertieren der Bits aktivieren.
