### ISSUE TITLE
Bit Timing ist unterschiedlich zwischen SDRPager und C9000 Pager

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/RasPagerC9000#3]
Wenn man mit beiden eine Aussendung des gleichen Inhalts macht, dann geht es mit dem DH3WR Skyper mit dem SDRPager und mit dem C9000 nicht.
Ein Vergleich des Audio-Daten zeigt bei Ausrichtung am Übergang Präambel->Anfang
![anfang](https://cloud.githubusercontent.com/assets/16710361/21328274/653feb4c-c633-11e6-94d5-4e318e87123d.PNG)

Am Ende sind die Daten aber deutlich verschoben
![ende](https://cloud.githubusercontent.com/assets/16710361/21328285/6f9382de-c633-11e6-9b38-7057ebb0e425.PNG)

Es muss noch herausgefunden werden, welche Variante jetzt richtig ist.

**Comment by dh3wr** [comment]
Ich habe mal die Timerwerte angeschaut und etwas verändert. Morgen mal testen. Siehe Commit 3b7001c4100b7289c22ec4d4a0dbcae68595bd90
@7h0ma5 Was sagst du dazu als Urheber des Codes?

**Comment by dh3wr** [comment]
Hmm, die Änderung hat den Versatz noch schlechter gemacht und nun ist auch kein Empfang mit dem DB6AC Skyper mehr möglich. Weitere Untersuchung notwendig.

**Comment by dh3wr** [comment]
@7h0ma5 Spricht etwas dagegen, einen 16 Bit Timer zu nehmen, um den Unterschied zwischen der "krummen Rate" von 1200 Baud und dem 8 MHz Clock zu haben? Mit 16 Bit und einem entsprechenden Prescaler sollte sich die Auflösung doch verbessern lassen, oder?

**Comment by dh3wr** [comment]
Nun, der RasPi commited zwar mit Thomas Identität, aber egal. Problem mit Commit 66040d1d9ba4988e30cfa8db10f434359954c17c gelößt. Timer 1 erzeugt nun mit reload-Wert 6666 -> 1199.94 Hz . Das ist schon deutlich näher dran als mit dem 8 Bit Timer2.

**Comment by 7h0ma5** [comment]
Ich hatte leider gerade erst Zeit mir das anzusehen. Die Lösung mit dem 16-Bit-Timer ist auf jedenfall wesentlich besser. Die Initialisierung des 8-Bit-Timers hatte ich aus dem Quellcode für den ATmega des Raspagers kopiert:

https://github.com/dh3wr/RasPagerDigi/blob/master/software/AVR%20FIFO/src/ATMega_FIFO.c#L163

Das könnte auch der Grund sein, warum die vom Raspager gesendeten Funkrufe auch nicht immer ankommen.
