### ISSUE TITLE
C9000 Interface sendet unkontrolliert bei Neustart

### ISSUE THREAD

**Issue by pe2kmv** [rwth-afu/RasPagerC9000#4]
Bei einem Neustart vom RPi sendet das C9000 Interface unkontrolliert. Nach dem Einsatz einer frischen Linux Distro ist das Problem immer noch da. Auch neu flashen vom Atmel löst das Problem nicht.

Siehe YouTube Link als Beispiel https://youtu.be/xQ-DuRGpMG4

**Comment by dh3wr** [comment]
Readme nicht gelesen. Du musst die serielle Ausgabe des Kernels abschalten

**Comment by dh3wr** [comment]
Readme vom unipager

**Comment by pe2kmv** [comment]
Stimmt... Letzter Abschnitt verpeilt...
Thanks!
